[project]
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.141.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.14.0",
    "python-dotenv>=1.2.3",
    "supabase>=2.31.0",
]
description = "Smartheating api"
name = "smart-api"
readme = "README.md"
requires-python = ">=3.14"
version = "0.1.0"

[tool.fastapi]
entrypoint = "app.main:app"
