id_fields = {
    "authUser": "email",
    "building": "id",
    "device": "deviceMappingId",
    "eventLog": "statusPageId",
    "floor": "id",
    "managedUser": "id",
    "meter": "id",
    "occupancySetting": "locationId",
    "presence": "locationId",
    "program": "id",
    "room": "id",
    "rule": "id",
    "season": "locationId",
    "systemActivation": "eventType",
    "tag": "id",
    "upcoming": "id",
    "upload": "id",
}
